modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/wendall911/SimpleTextOverlay/issues"
license="MIT"

[[mods]]
  modId="simpletextoverlay"
  displayName="Simple Text Overlay"
  description="Display extra information on top of your in-game screen."
  version="${version}"
  displayURL="https://github.com/wendall911/SimpleTextOverlay"
  updateJSONURL="https://raw.githubusercontent.com/wendall911/SimpleTextOverlay/1.19/files/updates.json"
  authors="wendall911"
  credits="DaftPVF, bspkrs, Lunatrius, ashar42"
  logoFile="logo.png"
  itemIcon="minecraft:compass"

[[dependencies.simpletextoverlay]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simpletextoverlay]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"
